version: '3.8'

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    env_file:
      - .env
    depends_on:
      - administration-clients
  administration-clients:
    image: "postgres:13-alpine"
    restart: always
    container_name: administration-clients-postgres-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=administration-clients-db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
